version: '3.1'
services:
  assessment-mysql-db:
    image: 'mysql:8.0'
    container_name: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'assessment'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '8b3b91c7'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
    - '3306:3306'
app_server:
  image: smart-hardware-shop
  container_name: app_server
  environment:
    spring.datasource.url: 'jdbc:mysql://host.docker.internal:3306/assessment'
  ports:
    - 8989:8989
  depends_on:
    - assessment-mysql-db
  links:
    - assessment-mysql-db
  restart: on-failure